version: 2.1
jobs:
  dist-build:
    parameters:
      npm_token:
        type: string
    docker:
      - image: circleci/node@sha256:64300d4fa16456a547e9e747a10e5eb02419a477ac08a592244dc5ca8adbda72 #shoud not have @ but breaks
    steps:
      - checkout
      - run:
          name: Create .npmrc file with NPM token to be able to build because we use private NPM packages
          command: |
            echo "//registry.npmjs.org/:_authToken=<< parameters.npm_token >>" > .npmrc
      - run: npm install
      - run:
          name: Installing the Vue CLI service to be able to build our project
          command: |
            sudo npm install -g @vue/cli
      - run:
          name: Project checks content of 3 folders in /public, but the must exist otherwise an error is thrown
          command: |
            [ -d "./public/erkende-standaard" ] && echo "Directory erkende-standaard exists" || mkdir -p ./public/erkende-standaard
            [ -d "./public/kandidaat-standaard" ] && echo "Directory kandidaat-standaard exists" || mkdir -p ./public/kandidaat-standaard
            [ -d "./public/geregistreerde-standaard" ] && echo "Directory geregistreerde-standaard exists" || mkdir -p ./public/geregistreerde-standaard
            [ -d "./public/standaard-in-ontwikkeling" ] && echo "Directory standaard-in-ontwikkeling exists" || mkdir -p ./public/standaard-in-ontwikkeling
      - run: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  upload:
    parameters:
      sas_token:
        type: string
      url:
        type: string
    docker:
      - image: circleci/python
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: cd $PWD/dist; bash ../scripts/azure.sh << parameters.sas_token >> <<parameters.url >>
workflows:
  version: 2
  publish-updated-content:
    jobs:
      - dist-build:
          npm_token: ${NPM_TOKEN}
      - upload:
          name: upload-test
          requires:
            - dist-build
          sas_token: ${SAS_TOKEN_TEST}
          url: https://swarmstoraccount.blob.core.windows.net/oslo-standards-register/dist.tar
      - hold:
          type: approval # presents manual approval button in the UI
          requires:
            - upload-test
      - upload:
          name: upload-prod
          requires:
            - hold
            - dist-build
          sas_token: ${SAS_TOKEN_PROD}
          url: https://swarmstoraccountprod.blob.core.windows.net/oslo-standards-register/dist.tar



