version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: ls -al
      - run: npm install
      - run: npm run build
      - run: ls -al
workflows:
  version: 2
  publish-updated-content:
    jobs:
      - build


