version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: ls -al
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - run: ls -al
workflows:
  version: 2
  publish-updated-content:
    jobs:
      - build


