version: 2
jobs:
  dist-build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Create .npmrc file with NPM token to be able to build because we use private NPM packages
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - run: npm install
      - run:
          name: Installing the Vue CLI service to be able to build our project
          command: |
            sudo npm install -g @vue/cli
      - run:
          name: Project checks content of 3 folders in /public, but the must exist otherwise an error is thrown
          command: |
            [ -d "./public/erkende-standaard" ] && echo "Directory erkende-standaard exists" || mkdir -p ./public/erkende-standaard
            [ -d "./public/kandidaat-standaard" ] && echo "Directory kandidaat-standaard exists" || mkdir -p ./public/kandidaat-standaard
            [ -d "./public/standaard-in-ontwikkeling" ] && echo "Directory standaard-in-ontwikkeling exists" || mkdir -p ./public/standaard-in-ontwikkeling
      - run: npm run build
      - persit_to_workspace:
          root: dist 
          paths: .
  upload:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run: cd $PWD/scripts; bash ./azure.sh ${SAS_TOKEN}
workflows:
  version: 2
  publish-updated-content:
    jobs:
      - dist-build
      - upload:
          requires:
            - dist-build


